### ISSUE TITLE
Custom skill to add vector fields cannot create indexes if data source is Table/Cosmos DB

### ISSUE THREAD

**Issue by nekozen** [Azure/cognitive-search-vector-pr#74]
### Overview
I have developped a custom skill to add vector fields into documents.
I tried it when creating index whose data source is in Azure Storage Account (BLOB), and it added vector fields successfully.
I also tried it for other indexes whose data sources are in Azure Storage Account (Table) or Cosmos DB, but it failed with the following errors:
"Could not map output field 'contentVector' to search index. Check the 'outputFieldMappings' property of your indexer."
(operation is "Projection.SearchIndex.OutputFieldMapping.contentVector")
I have tried various different definitions of outputFieldMappings and indexes, but have never had success.
Is the outputFieldMappings for vector fields supported for Azure Storage Account (Table) and Cosmos DB?

### Details
Here's snippets from my settings.

Added a vector field and its config into Index JSON.
```
{
  "name": "contentVector",
  "type": "Collection(Edm.Single)",
  "searchable": true,
  "filterable": false,
  "retrievable": true,
  "sortable": false,
  "facetable": false,
  "key": false,
  "indexAnalyzer": null,
  "searchAnalyzer": null,
  "analyzer": null,
  "normalizer": null,
  "dimensions": 1536,
  "vectorSearchConfiguration": "vectorConfig",
  "synonymMaps": []
}
...
"vectorSearch": {
  "algorithmConfigurations": [
    {
      "name": "vectorConfig",
      "kind": "hnsw",
      "hnswParameters": {
        "metric": "cosine",
        "m": 4,
        "efConstruction": 400,
        "efSearch": 500
      }
    }
  ]
}
...
```

Added WebApiSkill definition into Skillset definition.

```
{
  "@odata.type": "#Microsoft.Skills.Custom.WebApiSkill",
  "name": "embed",
  "description": null,
  "context": "/document",
  "uri": "https://...",
  "httpMethod": "POST",
  "timeout": "PT30S",
  "batchSize": 1,
  "degreeOfParallelism": null,
  "inputs": [
    {
      "name": "content",
      "source": "/document/content"
    }
  ],
  "outputs": [
    {
      "name": "vector",
      "targetName": "contentVector"
    }
  ],
  "httpHeaders": {}
}
```

The above uri is masked, but actually is the uri of Azure Function endpoint which creating vectors with the following response:
```
values=[{'recordId': '0', 'data': {'vector': [-0.017162053, -0.014763341, 0.014551301, -0.019984847, -0.007573833, 0.01179477, -0.016366901, -0.020753495, -0.026955688, -0.019852322, 0.012907985, -0.00060589, -0.007123246, -0.018010216, 
...]}, 'errors': None, 'warnings': None}]
```
Added outputFieldMappings into Indexer JSON.

```
  "outputFieldMappings": [
    {
      "sourceFieldName": "/document/vector",
      "targetFieldName": "contentVector"
    }
  ],
```

When I tried changing the custom skill and other definitions to use a string field instead of a vector field as an additional field, and I succeeded in creating an index for Storage Account Table. So, I think there's something wrong with the vector field (Cognitive Search's limitation or my wrong configuration)

**Comment by Careyjmac** [comment]
Are you changing the inputs of your custom skill definition when switching to the CosmosDB datasource? The input "/document/content" is the field where we place the text extracted from documents for the Blob datasource, where for CosmosDB and SQL we pull those initial sources based on the names from the CosmosDB document. So if your CosmosDB documents don't have a "content" field explicitly, then your skill definition is passing a null value for the "content" input to your custom skill endpoint. My hunch is that your custom skill implementation is returning a null "vector" when the input "content" is null with no additional warnings or errors, so we treat it like that was the intentional state, but then fail when trying to execute the outputFieldMappings.

My suggestion would be to double check the schema of your documents in CosmosDB, and make sure that you update the input source for your skill to match one of the fields in those documents (so if its called "text" in CosmosDB, change your skill input source to "/document/text"). I would also add a check in your custom endpoint implementation that will return a warning value if the input "content" is null or empty, so that you can see some signal of that in the indexer execution history and make debugging something like this easier in the future.

**Comment by gmndrg** [comment]
@nekozen were you able to resolve the issue above? Please reach out to us so we can offer a different way to do this with an upcoming feature that helps you chunk and vectorize easily. You can open a support case from the Azure portal and our support team will help providing all the info you need to deploy the new feature. You can refer them to this post. Thank you!

**Comment by nekozen** [comment]
I'm sorry for late reply. Thank you for your comments: @gmndrg @Careyjmac 
My CosmosDB documents had a "content" field.
But now I have changed the way of adding vector fields. Without custom skills, documents including vector fields are pushed into   Cognitive Search directly.
I have also confirmed AzureOpenAIEmbeddingSkill is available on 2023-10-01-Preview API.
https://learn.microsoft.com/en-us/rest/api/searchservice/skillsets/create?view=rest-searchservice-2023-10-01-preview&tabs=HTTP#azureopenaiembeddingskill

So, I close this issue.
