### ISSUE TITLE
Office Documents not supported?

### ISSUE THREAD

**Issue by levalencia** [Azure/cognitive-search-vector-pr#82]
When I analyzed the code for the Open AI Embedding Generator I see this:

```
    FILE_FORMAT_DICT = {
        "md": "markdown",
        "txt": "text",
        "html": "html",
        "shtml": "html",
        "htm": "html",
        "py": "python",
        "pdf": "pdf",
    }
    SENTENCE_ENDINGS = [".", "!", "?"]
    WORDS_BREAKS = ['\n', '\t', '}', '{', ']', '[', ')', '(', ' ', ':', ';', ',']
    TOKEN_ESTIMATOR = TokenEstimator()

    def _get_file_format(self, file_path: str) -> Optional[str]:
        """Gets the file format from the file name.
        Returns None if the file format is not supported.
        Args:
            file_path (str): The file path of the file whose format needs to be retrieved.
        Returns:
            str: The file format.
        """
        # in case the caller gives us a file path
```

So word and pptx files are not supported at this time?

**Comment by arv100kri** [comment]
You are referring to this - https://github.com/Azure-Samples/azure-search-power-skills/blob/main/Vector/EmbeddingGenerator/chunker/text_chunker.py

We haven't tested langchain's recursive text splitter with anything other than the formats listed there, which is why docx and pptx don't show up there... You can try adding them to see if they are effective for your scenario...

**Comment by levalencia** [comment]
actually its supported, I tested docx and pptx! and the embeddings are generated
