### ISSUE TITLE
API for creating Vector Indexers

### ISSUE THREAD

**Issue by Mano1192** [Azure/cognitive-search-vector-pr#92]
Maybe this already exists in the API but I was unable to find it. Once an index is created the acs vector search works great. Having an Indexer that can be run as an azure function on a frequency (hourly, daily, weekly etc.) would allow us to keep the data up to date given new files added or removed from an index's datasource.

Is this possible today, and if not can this be added to the backlog?

Currently I have a self rolled file chunker that can handle multiple file types (.txt, .pdf, .doc, .docx etc) and looking to figure out how to run this on a frequency to keep the vectors up to date. Thinking an azure function tied into a power automate frequency might be the way to go but hoping theres already something in the works in this area. Thanks and great job getting vectors into ACS!!

**Comment by gmndrg** [comment]
Hello @Mano1192 you can use today a custom skill in order to perform this task, you can see an end to end example here of how to accomplish this: https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-ingestion-python-sample.ipynb

However, we definitely have some changes coming up in the coming months to support this in a most efficient way and without having multiple indexes. I hope this helps.

**Comment by gmndrg** [comment]
I will be marking this as closed since workaround was provided and feedback also taken for a feature that supports this natively.
